#+title: Polishing the Particle System
#+date: [2022-04-26]
#+slug: 2022-04-26

*Today's goal:* Add new features to particle system implementation and implement a few more effects!

[[yt:VxJ6C0s7ku0][Watch the recording on YouTube!]]

* It works!  Now what?

In the last stream, we implemented a particle system from scratch and verified it worked by adding a ship booster effect for the player ship in Syphon Break.

Today we'll expand on that implementation to add a few more features and then use it to add specific effects to make the game look more interesting.

Check out the code:
https://github.com/FluxHarmonic/syphon-break
https://github.com/substratic/engine
https://github.com/mesche-lang/compiler

* Tasks

** DONE Fix the garbage collector crashing issue
CLOSED: [2022-04-26 Tue 18:26]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-04-26 Tue 18:26]
:END:
** DONE Add opacity interpolation
CLOSED: [2022-04-26 Tue 18:49]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-04-26 Tue 18:49]
:END:
** DONE Add a speed boost effect
CLOSED: [2022-04-26 Tue 19:09]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-04-26 Tue 19:09]
:END:
** TODO Add an option for a particle system to always have particles follow origin
** TODO Add an explosion effect when a ship is destroyed
** TODO Add a burning effect for heatwaved enemies
** TODO Add particle effects for enemy ship boosters?
** TODO Add color interpolation
