#+title: Rewriting the Game Build with Mesche
#+date: [2022-03-15]
#+slug: 2022-03-15

*Today's goal:* Convert the build for Crash The Stack and Substratic to use the new =mesche build= command!

[[yt:neK34BxJz3g][Watch the recording on YouTube!]]

* Updates

- Fixed /a ton/ of issues in the compiler and VM by writing more code in the language
- Added a lot of useful core APIs in the =mesche fs=, =mesche list=, =mesche string= and =mesche process= modules
- =mesche build= is ready to be used...

* Building Projects with Mesche

I spent a lot of time this weekend fleshing out the Mesche language and libraries to accomplish a very important goal: the ability to build an entire C and Mesche project using my own build tool and project description format.

Why?  To make it much easier to write and ship projects using Mesche!

Building this tool allows me to simplify the approach I use to build my projects consistently across multiple platforms and also handle things like dependency management, release configurations, and packaging apps for distribution.

Today I'll show you how it works by converting the build of Crash The Stack and the Substratic library to using =mesche build=.

If you want to check out the code:
- https://github.com/mesche-lang/cli
- https://github.com/mesche-lang/cli/blob/df63638008a20f2859026f2c16709f72e1d56d3e/modules/mesche/build.msc

* Tasks

** DONE Create a new =project.msc= file for Crash The Stack
CLOSED: [2022-03-15 Tue 18:13]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-03-15 Tue 18:13]
:END:
** DONE Create a new =project.msc= file for the embedded Substratic library
CLOSED: [2022-03-15 Tue 18:13]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-03-15 Tue 18:13]
:END:
** DONE Add a function to make it easy to clone a Git repository
CLOSED: [2022-03-15 Tue 18:21]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-03-15 Tue 18:21]
:END:
** DONE Add a function for downloading a file (musl-c) from the web using =wget=
CLOSED: [2022-03-15 Tue 18:31]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-03-15 Tue 18:31]
:END:
** DONE Add a function for unpacking a .tar.gz file using =tar=
CLOSED: [2022-03-15 Tue 18:33]
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-03-15 Tue 18:33]
:END:
** TODO Add a way to switch between =gcc= and =musl-c=
** TODO Delete the old build.sh file!

* Notes

Check out the commits we made in this stream:

- https://github.com/mesche-lang/cli/commit/bed3caa6d81840d7f00a369c2e5ffb7cffaa4e36
- https://github.com/FluxHarmonic/crash-the-stack/commit/8070d3a28d3b4965096ea331515a5d11e136089c

* Next Steps
